if(new URLSearchParams(location.search).has('paneltest'))(async()=>{
const wait=ms=>new Promise(r=>setTimeout(r,ms)),results=[];const check=(name,pass)=>{results.push({name,pass:!!pass});if(!pass)throw Error(name);};
try{await wait(650);const h=document.querySelector('#bili-ambient-ui'),s=h.shadowRoot,$=id=>s.getElementById(id),p=$('panel');const before=[document.documentElement.scrollWidth,document.documentElement.scrollHeight],baselineY=$('toggle').getBoundingClientRect().y;
$('toggle').click();await wait(35);check('opening animates opacity and transform',p.getAnimations().length>0&&!p.hidden&&p.dataset.state==='open');check('opening leaves page dimensions unchanged',before[0]===document.documentElement.scrollWidth&&before[1]===document.documentElement.scrollHeight);await wait(260);while(getComputedStyle(p).transform!=='none')await wait(20);check('opened panel is accessible',!p.inert&&$('toggle').getAttribute('aria-expanded')==='true'&&s.activeElement===$('enabled'));check('floating trigger stays anchored',$('toggle').getBoundingClientRect().y===baselineY);check('horizontal panel scrolling is disabled',getComputedStyle(p).overflowX==='hidden');
const dims=[p.clientWidth,p.clientHeight],origin=$('enabled').getBoundingClientRect();$('enabled').click();let maxOverflow=0,maxShift=0;const t=performance.now();while(performance.now()-t<650){await wait(20);maxOverflow=Math.max(maxOverflow,p.scrollWidth-p.clientWidth);maxShift=Math.max(maxShift,Math.abs(p.clientWidth-dims[0]),Math.abs(p.clientHeight-dims[1]),Math.abs($('enabled').getBoundingClientRect().y-origin.y));}
check('switch pulse never exceeds panel width',maxOverflow===0);document.body.dataset.panelShift=JSON.stringify({dims,maxShift,after:[p.clientWidth,p.clientHeight],origin:origin.toJSON(),afterOrigin:$('enabled').getBoundingClientRect().toJSON(),transform:getComputedStyle(p).transform,status:$('status').textContent});check('switch never changes panel space',maxShift<.1);const w=document.querySelector('#halo-page-wave');check('wave stays aligned to stable switch',w&&Math.abs(Number(w.dataset.originX)-(origin.left+origin.width/2))<1&&Math.abs(Number(w.dataset.originY)-(origin.top+origin.height/2))<1);
$('close').click();await wait(35);check('closing visibly animates before unmount',!p.hidden&&p.getAnimations().length>0);check('closing removes focusability immediately',p.inert&&s.activeElement===$('toggle')&&$('toggle').getAttribute('aria-expanded')==='false');await wait(260);check('close unmounts after animation',p.hidden);
$('toggle').click();await wait(45);$('toggle').click();await wait(45);$('toggle').click();await wait(300);check('rapid reopen cancels stale close',!p.hidden&&!p.inert&&p.dataset.state==='open');check('reopen leaves document space unchanged',before[0]===document.documentElement.scrollWidth&&before[1]===document.documentElement.scrollHeight);
$('close').click();await wait(260);$('toggle').click();$('enabled').click();await wait(60);const wave=document.querySelector('#halo-page-wave'),r=$('enabled').getBoundingClientRect();document.body.dataset.panelGeometry=JSON.stringify({wave:wave?.dataset,rect:r.toJSON(),transform:getComputedStyle(p).transform,enabled:$('enabled').checked});check('wave settles unfinished panel entry',wave&&Math.abs(Number(wave.dataset.originY)-(r.top+r.height/2))<1);
}catch(e){results.push({name:e.message,pass:false});}document.body.dataset.panelResults=JSON.stringify(results);
})();
