const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),zlib=require('node:zlib');
const source=fs.readFileSync(__dirname+'/../src/scripts/halo-local-update.js','utf8');
const scope={TextDecoder,TextEncoder,DataView,Uint8Array,Map,Blob,DecompressionStream,crypto:globalThis.crypto,setTimeout,clearTimeout,AbortController,URL};
vm.runInNewContext(source,scope);const updater=scope.HaloLocalUpdate;
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(entries){const locals=[],centrals=[];let offset=0;for(const [path,plain] of entries){const name=Buffer.from(path),raw=Buffer.from(plain),data=zlib.deflateRawSync(raw),crc=crc32(raw),h=Buffer.alloc(30),c=Buffer.alloc(46);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(8,8);h.writeUInt32LE(crc,14);h.writeUInt32LE(data.length,18);h.writeUInt32LE(raw.length,22);h.writeUInt16LE(name.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(8,10);c.writeUInt32LE(crc,16);c.writeUInt32LE(data.length,20);c.writeUInt32LE(raw.length,24);c.writeUInt16LE(name.length,28);c.writeUInt32LE(offset,42);locals.push(h,name,data);centrals.push(c,name);offset+=h.length+name.length+data.length;}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);const b=Buffer.concat([...locals,central,end]);return b.buffer.slice(b.byteOffset,b.byteOffset+b.length);}
const manifest={name:'映光 Halo',version:'1.3.1',manifest_version:3,permissions:['storage'],host_permissions:['https://www.youtube.com/*'],background:{service_worker:'scripts/background.js'}};
const files=()=>new Map([['manifest.json',new TextEncoder().encode(JSON.stringify(manifest))],['scripts/background.js',new TextEncoder().encode('void 0;')]]);
test('extracts a real compressed ZIP with CRC and exact paths',async()=>{const entries=[['Chrome/manifest.json',JSON.stringify(manifest)],['Chrome/scripts/background.js','void 0;']];const result=await updater.unzip(zip(entries));assert.equal(result.size,2);assert.equal(new TextDecoder().decode(result.get('scripts/background.js')),'void 0;');});
for(const path of ['Chrome/../outside.js','Chrome/scripts/../../x.js','Other/manifest.json','Chrome/scripts\\x.js'])test('rejects traversal or foreign root '+path,async()=>{await assert.rejects(updater.unzip(zip([[path,'bad'],['Chrome/manifest.json','{}']])),/unsafe_path/);});
test('rejects duplicate paths and corrupted compressed bytes',async()=>{await assert.rejects(updater.unzip(zip([['Chrome/manifest.json','{}'],['Chrome/manifest.json','{}']])),/invalid_package/);const b=zip([['Chrome/manifest.json','{}']]);new Uint8Array(b)[50]^=255;await assert.rejects(updater.unzip(b));});
test('requires exact target version and all referenced resources',()=>{assert.equal(updater.validate(files(),manifest,'1.3.1').version,'1.3.1');assert.throws(()=>updater.validate(files(),manifest,'1.3.2'),/wrong_package/);const missing=files();missing.delete('scripts/background.js');assert.throws(()=>updater.validate(missing,manifest,'1.3.1'),/invalid_package/);});
test('rejects new permissions, hosts and external message access',()=>{for(const change of [{permissions:['storage','tabs']},{host_permissions:['<all_urls>']},{externally_connectable:{matches:['*://*/*']}}]){const f=files();f.set('manifest.json',new TextEncoder().encode(JSON.stringify({...manifest,...change})));assert.throws(()=>updater.validate(f,manifest,'1.3.1'),/new_permissions/);}});
test('download requires publisher SHA256 before fetching',async()=>{await assert.rejects(updater.download('https://github.com/Elys1an-Y1san/Halo/releases/download/v1.3.1/Halo-Chrome-1.3.1.zip',undefined,()=>{}),/missing_digest/);await assert.rejects(updater.download('https://evil.example/package.zip','a'.repeat(64),()=>{}),/missing_digest/);});
test('rejects a transport-successful package with wrong SHA256',async()=>{const url='https://github.com/Elys1an-Y1san/Halo/releases/download/v1.3.1/Halo-Chrome-1.3.1.zip';scope.fetch=async()=>({ok:true,url,body:new Blob(['bad']).stream()});await assert.rejects(updater.download(url,'a'.repeat(64),()=>{}),/digest_mismatch/);});
function diskHarness(failAfter=Infinity){
 const disk=new Map([['manifest.json',Buffer.from('old manifest')],['scripts/background.js',Buffer.from('old runtime')]]),saved=new Map();let writes=0;
 scope.indexedDB={open(){const r={};queueMicrotask(()=>{r.result={close(){},transaction(){const tx={};tx.objectStore=()=>({get(k){const req={result:saved.get(k)};queueMicrotask(()=>tx.oncomplete());return req;},put(v,k){saved.set(k,v);queueMicrotask(()=>tx.oncomplete());return{};},delete(k){saved.delete(k);queueMicrotask(()=>tx.oncomplete());return{};}});return tx;}};r.onsuccess();});return r;}};
 const dir=(prefix='')=>({async getDirectoryHandle(n){return dir(prefix+n+'/');},async getFileHandle(n,{create=false}={}){const key=prefix+n;if(!disk.has(key)&&!create)throw new DOMException('missing','NotFoundError');return{async getFile(){return new Blob([disk.get(key)||'']);},async createWritable(){let bytes;return{async write(b){if(++writes===failAfter)throw Error('disk_full');bytes=b;},async close(){disk.set(key,bytes);},async abort(){}};}};},async removeEntry(n){disk.delete(prefix+n);}});
 return{disk,saved,dir:dir()};
}
test('failed write rolls back every original file and removes added files',async()=>{const h=diskHarness(2),next=files();next.set('new.js',new TextEncoder().encode('new'));await assert.rejects(updater.install(h.dir,next,()=>{}),/disk_full/);assert.equal(new TextDecoder().decode(h.disk.get('manifest.json')),'old manifest');assert.equal(new TextDecoder().decode(h.disk.get('scripts/background.js')),'old runtime');assert(!h.disk.has('new.js'));assert(!h.saved.has('journal'));});
test('successful install commits manifest last and clears recovery state',async()=>{const h=diskHarness(),steps=[];await updater.install(h.dir,files(),n=>steps.push([n,new TextDecoder().decode(h.disk.get('manifest.json'))]));assert.equal(steps[0][1],'old manifest');assert.equal(JSON.parse(steps.at(-1)[1]).version,'1.3.1');assert(!h.saved.has('journal'));});
test('existing interrupted transaction blocks another install',async()=>{const h=diskHarness();h.saved.set('journal',{dir:h.dir,backup:[]});await assert.rejects(updater.install(h.dir,files(),()=>{}),/recovery_required/);assert.equal(new TextDecoder().decode(h.disk.get('manifest.json')),'old manifest');});
